### ISSUE TITLE
Generation of point cloud data for static file server

### ISSUE THREAD

**Issue by jcsmik** [sony/mapray-js#244]
Can you please provide more details on generating pointcloud data for static file server?

**Comment by daisuke201** [comment]
Thank you for your question.
PointCloud data is Mapray's proprietary tile format.
The web service called [Mapray Cloud](https://cloud.mapray.com/) can generate this format from LAS and PLY.
The PointCloud sample with Mapray Cloud is as follow.
https://github.com/sony/mapray-js/tree/master/debug/point-cloud
However, currently, this service's target is in Japan, we haven't provide it for outside Japan.
We have plan to prepare a file format document, but the file format has not been completely fixed yet, 
so it will be provided after it is officially fixed.

**Comment by smikkysingh** [comment]
Thank You for the reply.

**Comment by jcsmik** [comment]
Thank you for the reply.

**Comment by DaneshwariTalikoti** [comment]
Currently, when trying to view the point cloud (uploaded our own ply file in mapray cloud) using the files in example/pointcloud and debug/point-cloud. 
I observe black screen and the error I get is “invalid request”, when fetch(this._makeURL…..) is being called in CloudDemProvider.js. 

Does this error occur because of not able to access service target which is in Japan, or could this be because of 3D tile format issue. 
(Please note that, I didn’t face any conversion issues after uploading the ply to the cloud )
